version: "2.1"
orbs:
  go: circleci/go@1.11.0
jobs:
  build:
    executor:
      name: go/default
      tag: "1.16"
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run: go test -v
workflows:
  main:
    jobs:
      - build
